# Generated by Django 4.2.16 on 2024-09-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamescore',
            unique_together={('game', 'player')},
        ),
    ]
