# Generated by Django 4.2.16 on 2024-09-19 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_gamescore_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_change', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to='app.gamescore')),
            ],
        ),
    ]
